{% set name = "nequip" %}
{% set version = "0.13.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nequip-{{ version }}.tar.gz
  sha256: 2b24c02da50bad9520d3aa4316ca55078912fbd0b783a44202021b37f8b07978

build:
  entry_points:
    - nequip-train = nequip.scripts.train:main
    - nequip-evaluate = nequip.scripts.evaluate:main
    - nequip-benchmark = nequip.scripts.benchmark:main
    - nequip-deploy = nequip.scripts.deploy:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - hydra-core
    - lightning
    - lmdb
    - python-lmdb
    - matscipy
    - pytorch >=2.2.0
    - torchmetrics >=1.6.0
    - typing_extensions
    - python >={{ python_min }}
    - numpy
    - ase
    - tqdm
    - e3nn >=0.5.6,<0.6.0
    - pyyaml
    - importlib-metadata
    - torch-runstats >=0.2.0
    - torch-ema >=0.3.0

test:
  imports:
    - nequip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mir-group/nequip
  summary: NequIP is a code for building E(3)-equivariant interatomic potentials
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mir-group/nequip
  dev_url: https://github.com/mir-group/nequip

extra:
  recipe-maintainers:
    - jan-janssen
