{% set name = "nequip" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nequip-{{ version }}.tar.gz
  sha256: f805a29fb0631f1134cd19027055f726c5e50e531cc46bd1a872bda91378edb2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >3.7
  run:
    - ase
    - e3nn <0.5.0,>=0.3.5
    - numpy
    - python >3.7
    - pyyaml
    - scikit-learn <=1.0.1
    - pytorch !=1.9.0,<=1.12,>=1.8
    - torch-ema >=0.3.0
    - torch-runstats >=0.2.0
    - tqdm
    - typing-extensions

test:
  imports:
    - nequip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mir-group/nequip
  summary: NequIP is a code for building E(3)-equivariant interatomic potentials
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mir-group/nequip
  dev_url: https://github.com/mir-group/nequip

extra:
  recipe-maintainers:
    - jan-janssen
